apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbctest413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbctest413
    app.kubernetes.io/part-of: fbctest
  name: fbctest413
  namespace: user1-tenant
spec:
  port:
    targetPort: 50051
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fbctest413
    weight: 100
status: {}
